services:
  # caddy:
  #   image: caddy:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - frontend
  #     - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8090:8090"
    volumes:
      - ./backend:/testy
      - /var/run/docker.sock:/var/run/docker.sock
      - submissions:/submissions
    depends_on:
      - postgres

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     target: dev
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - WATCHPACK_POLLING=true # uncomment if hot reload misses changes (common on Windows/WSL)

  postgres:
    ports:
    - "5432:5432"
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: testy
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  submissions:
    name: testy_submissions
  caddy_data:
  caddy_config:
